apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: kykil/spring:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring
  namespace: argocd
spec:
  selector:
    app: spring
  ports:
  - port: 8080
